### ISSUE TITLE
MDN description shows up as "A web testing deep dive: The MDN web testing report....."

### ISSUE THREAD

**Issue by harshyogesh** [mdn/yari#3643]
Hello

I am not sure if its intentional but a search for MDN in the google has the following description shown up for the MDN 

"A web testing deep dive: The MDN web testing report For the last couple of years, we've run the MDN Web Developer Needs Assessment (DNA) Report, which aims to highlight the key issues faced by developers building...."

![Capture](https://user-images.githubusercontent.com/40065062/116179786-8e73ef80-a735-11eb-8eea-524e5cc0d3d5.PNG)
![Capture2](https://user-images.githubusercontent.com/40065062/116179812-97fd5780-a735-11eb-8e6d-f918bd92cda0.PNG)

Attached screenshot for reference

**Comment by peterbe** [comment]
That was when we had the banner there. It was temporary. Unfortunate that Google snapped that up.

Seems it's fixed now. At least for me from here. Might require a couple more days of "patience"
<img width="1273" alt="Screen Shot 2021-04-27 at 4 34 56 PM" src="https://user-images.githubusercontent.com/26739/116309397-b5064a80-a776-11eb-9aa2-915eab16b569.png">

Thanks for the heads up!!

**Comment by harshyogesh** [comment]
thanks for the information, I think its demanding more of that virtue on my side as its still showing the same for me !

**Comment by peterbe** [comment]
> thanks for the information, I think its demanding more of that virtue on my side as its still showing the same for me !

Gee! I hope it "corrects" itself. Soon. 

But it's certainly an interesting problem because we have more and other future plans to temporarily show banners and stuff which might "negatively" affect how Google describes MDN in search results.

**Comment by harshyogesh** [comment]
If its not pulling someone's leg, I can keep pinging here in some days' interval until it goes away as I am learning and every morning I need to go to MDN :D

**Comment by peterbe** [comment]
> If its not pulling someone's leg, I can keep pinging here in some days' interval until it goes away as I am learning and every morning I need to go to MDN :D

Much appreciated.

**Comment by harshyogesh** [comment]
With little inconsistency last week, now its showing correctly for last 3 days !
