### ISSUE TITLE
Fix "Page not found" suggested search path

### ISSUE THREAD

**Issue by harrisi** [mdn/yari#8822]
### Summary

When a page is not found, a "Page not found" page is served, with a section for suggested search terms by generating links to ``window.location.pathname.split('/').map(el => `https://developer.mozilla.org/${window.location.pathname.split('/')[1]}/search?q=${el}`).splice(2)`` (this is obviously not how it's actually done on the server, but just to show what's happening). This is includes the top-most level of the path, which either shouldn't be included in the links generated, as it causes the path to be something like `https://developer.mozilla.org/docs/search?q=Quirks%20Mode%20and%20Standards%20Mode`, with `docs` included, whereas the search path is just `/search` (i.e., top-level).

### URL

https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

### Reproduction steps

1. Navigate to https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
2. Click on any link in the suggested search section

### Expected behavior

Should navigate to https://developer.mozilla.org/en-US/search?q=Quirks%20Mode%20and%20Standards%20Mode

### Actual behavior

Navigates to https://developer.mozilla.org/en-US/docs/search?q=Quirks%20Mode%20and%20Standards%20Mode

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by harrisi** [comment]
Interesting. I just tried this with curl and Chrome and I do indeed get redirected to the proper `en-US` page.

It seems the issue is that I'm logged into MDN Plus on Firefox. I'll look into that more.

**Comment by caugner** [comment]
> It seems the issue is that I'm logged into MDN Plus on Firefox.

Do you have MDN Offline enabled by any chance?

**Comment by harrisi** [comment]
Yes, which does seem to be the issue. That seems like a big enough difference in cause to warrant a new issue.

**Comment by caugner** [comment]
@harrisi This seems to have been fixed with https://github.com/mdn/yari/pull/8846, I can not reproduce it (with MDN Offline enabled). Would you mind trying it again? (I tested with https://developer.mozilla.org/docs/Web/HTML/Quirks)

**Comment by harrisi** [comment]
I'm still seeing this. I tried clearing my cache and getting rid of any local storage, redownloading, and testing again. Tried in a different browser, in private mode, still seeing the issue.

Interestingly, if I sign in in a Safari private window, turn on offline content, and before even downloading the content, navigate to https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode, I see the issue. If I turn off offline content and go to the address again, it redirects correctly.

I'm still not sure how to even effectively recreate this locally, actually. Any tips on mocking a signed in user, using local storage rather than local web server, etc. would be appreciated.

**Comment by caugner** [comment]
Thank you for the update. Can you explain how you navigate to https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode in the first place (and not https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode, which would work)?

**Comment by harrisi** [comment]
1. Open a page that is in quirks mode (or Almost Standards mode) in Firefox (e.g., https://www.quirksmode.org/)
2. View console output
3. Click on [Learn More] in console

**Comment by caugner** [comment]
Added `effort: large`, as the only solution I see is to add redirect support to MDN Offline. If we only add the missing locale (ignoring the `_redirects.txt` in content), then this could be `effort: medium`.

**Comment by caugner** [comment]
Fwiw, the link is in the Firefox source code: https://searchfox.org/mozilla-central/rev/1b79e3d893035e3ab581401bc70f2e5198c2fa73/devtools/server/actors/errordocs.js#140-141

**Comment by harrisi** [comment]
I think that's fine, right? It's still the issue of redirecting to a set locale in offline mode, I think?

I didn't mention it before, but I seem to recall experiencing this when navigating to a link with a locale in the URL other than the one I had set. Unfortunately I'm not currently paying for MDN Plus so I can't confirm the originally described behavior or the wrong-locale issue still exists.

This seems obscure enough that it seems like quite low priority. It still seems like a bug, so I'm hesitant to suggest closing it. I was trying to think of a way to clarify the title/body of the issue to be more clear. It's still searchable by any combination of something like "offline locale redirect" so it seems useful to exist, at least. I personally don't have time to work on it, and I don't remember ever figuring out how to test this locally in the first place.

As a side note, I very much appreciate an update after all this time - and I also hope I didn't cause you any wasted cycles thinking about this too much. :)
