### ISSUE TITLE
Blog links appear as links to unwritten pages

### ISSUE THREAD

**Issue by bozoputer** [mdn/yari#9345]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/landmark_role

### What specific section or headline is this issue about?

# See Also

### What information was incorrect, unhelpful, or incomplete?

The link [Using HTML landmark roles to improve accessibility](https://developer.mozilla.org/en-US/blog/aria-accessibility-html-landmark-roles/) on MDN blog (2023) is styled in red with a squiggly underline and a tooltip that says it is a link to an unwritten page, however, that is no longer the case, as the page has been written.

### What did you expect to see?

The link styled in a similar fashion as those preceding it.

### Do you have any supporting links, references, or citations?

N/A

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/landmark_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/landmark_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/landmark_role/index.md
* Last commit: https://github.com/mdn/content/commit/07f0cf4375aaa02e1071d8bd0e8518db7609b7a9
* Document last modified: 2023-07-17T23:05:13.000Z

</details>

**Comment by yin1999** [comment]
This flaws system's issue should be fixed by #9080. I've tested this locally :)

![image](https://github.com/mdn/yari/assets/15844309/c5d9fb12-aed9-42d1-8a57-866486d96f52)

**Comment by caugner** [comment]
Looks like https://github.com/mdn/yari/pull/9080 didn't fix it on production. 😕
