### ISSUE TITLE
Country Blocking limits access to interactive-examples.mdn.mozilla.net

### ISSUE THREAD

**Issue by erosman** [mdn/yari#9378]
### Summary

It appears that the server serving the interactive examples on MDN, engages in country blocking.

The interactive examples are blocked with some Country IPs and allowed when using a proxy from other countries.

Country blocking is not uncommon. 
- Github limits access based on location
- Google docs has been blocking some countries for many years
- There are many other sites that actively block country ranges

Please note that usually, when there is a country block set-up, it will not be limited to a single country.
Please also note that country blocking is usually politically motivated.

See also: [Google restricts access to some of its business services in certain countries or regions](https://support.google.com/a/thread/6636891/google-restricts-access-to-some-of-its-business-services-in-certain-countries-or-regions)

### URL

Any MDN document with an interactive example e.g. [minmax()](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax)

Interactive Example: https://interactive-examples.mdn.mozilla.net/pages/css/function-minmax.html

Result with blocked IPs:

![image](https://github.com/mdn/yari/assets/6458876/760420f7-b465-4f35-8694-43055ac0e97d)

![image](https://github.com/mdn/yari/assets/6458876/bcd67503-8647-4b4e-a0ce-85a105193b9b)

### Reproduction steps

Reproducing it requires IPs/Proxies from multiple countries. 

1. Test with an IP from a location that is blocked
2. Test with an IP from a location that is not blocked

### Expected behavior

Open Source initiatives from Mozilla is expected to be accessible to all users.

### Actual behavior

The interactive examples are not accessible in some countries.

### Device

Desktop

### Browser

Firefox

### Browser version

Pre-release (e.g. Beta, Nightly or Canary)

### Operating system

Linux

### Anything else?

It is understandable that the configuration of the Google servers are not under the control of Mozilla. However, universal accessibility of the MDN materials is worth considering.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Thank you for reporting this issue @erosman and sorry for taking so long to get back to you.

Can you tell us from what countries you were accessing MDN when you experienced the problem? Are you still having the problem?

Once we have these information, we will talk to our infrastructure team to see what we can do about this.

**Comment by erosman** [comment]
> Can you tell us from what countries you were accessing MDN when you experienced the problem?

As mentioned, Country Blocking is never limited to a single country. It is a server setting and server admin knows very well which country (IP ranges) they have blocked.
You can try countries that are subject to US sanctions, for example.

Furthermore, it is not something that Mozilla developers can easily test, unless they have a proxy for that country, which is often hard to get.

> Are you still having the problem?

I tested it again just now and it is still an issue.

**Comment by caugner** [comment]
Thank you for the quick reply @erosman.

Three more questions:

1. Can you tell me if the interactive examples never load, or do they sometimes load?
2. Does https://interactive-examples.mdn.mozilla.net/pages/css/border-style.html load?
3. Does https://mdn.dev/ load?

**Comment by erosman** [comment]
> Can you tell me if the interactive examples never load, or do they sometimes load?

Due to browser caching, they sometimes appear to load but with hard refresh, it fails.

> Does https://interactive-examples.mdn.mozilla.net/pages/css/border-style.html load?

No

![image](https://github.com/mdn/yari/assets/6458876/6ede1bf6-bdd0-41b1-bc1e-3d708c6d4092)


> Does https://mdn.dev/ load?

No

![image](https://github.com/mdn/yari/assets/6458876/fdc42e3a-89c7-4199-bf79-0fb9ca4e9ea9)


See also:

![image](https://github.com/mdn/yari/assets/6458876/12ff148f-bbd2-4965-b352-b8360a265dc7)

**Comment by caugner** [comment]
@erosman The issue should be resolved now, could you please test once more? Thank you! 🙏

**Comment by erosman** [comment]
The issue is still present.

Tested with:
- Firefox Nightly 120.0a1 (2023-10-17) (64-bit)
- Firefox 118.0.2 (64-bit) clean profile without any addons
- Chrome Version 118.0.5993.88 (Official Build) (64-bit) clean profile without any addons

**Comment by erosman** [comment]
It is indeed fixed.
Thank you for fixing it.
